{"name":"C. Try and Catch","group":"Codeforces - Codeforces Round 123 (Div. 2)","url":"https://codeforces.com/contest/195/problem/C","interactive":false,"memoryLimit":256,"timeLimit":2000,"tests":[{"input":"8\ntry\n    try\n        throw ( AE )\n    catch ( BE, \"BE in line 3\")\n\n    try\n    catch(AE, \"AE in line 5\")\ncatch(AE,\"AE somewhere\")\n","output":"AE somewhere\n","id":1728316195977},{"input":"8\ntry\n    try\n        throw ( AE )\n    catch ( AE, \"AE in line 3\")\n\n    try\n    catch(BE, \"BE in line 5\")\ncatch(AE,\"AE somewhere\")\n","output":"AE in line 3\n","id":1728316196019},{"id":1728316195967,"input":"8\ntry\n    try\n        throw ( CE )\n    catch ( BE, \"BE in line 3\")\n\n    try\n    catch(AE, \"AE in line 5\")\ncatch(AE,\"AE somewhere\")\n","output":"Unhandled Exception\n"}],"testType":"single","input":{"type":"stdin"},"output":{"type":"stdout"},"languages":{"java":{"mainClass":"Main","taskClass":"CTryAndCatch"}},"batch":{"id":"b1c979f0-7ef9-4557-a6d8-0f868f5746d9","size":1},"srcPath":"c:\\Users\\ganes\\Documents\\prg\\codeforces\\jts\\C_Try_and_Catch.cpp"}